# Generated by Django 6.0.4 on 2026-04-15 18:53

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['grade_level'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_type', models.CharField(choices=[('PROFESSOR', 'Professor'), ('STAFF', 'Administrative Staff')], max_length=10)),
                ('cin', models.CharField(max_length=15, unique=True, validators=[apps.core.validators.validate_cin])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent (Titulaire)'), ('CONTRACT', 'Contractual (Contractuel)'), ('TEMPORARY', 'Temporary (Vacataire)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('CV', 'Curriculum Vitae'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('ID_COPY', 'ID Copy'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(max_length=200)),
                ('research_area', models.CharField(blank=True, max_length=300)),
                ('academic_rank', models.CharField(max_length=100)),
                ('publications_count', models.PositiveIntegerField(default=0)),
                ('teaching_hours_per_week', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to='employees.employee')),
            ],
            options={
                'db_table': 'professor_profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=200)),
                ('office_number', models.CharField(blank=True, max_length=20)),
                ('work_schedule', models.CharField(blank=True, max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='employees.employee')),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
    ]
