# Generated by Django 6.0.4 on 2026-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='numero_somme',
            field=models.CharField(blank=True, help_text='Numero de somme (PPR) du fonctionnaire.', max_length=20, null=True, unique=True),
        ),
    ]
