# Generated by Django 6.0.4 on 2026-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_numero_somme'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
