# Generated by Django 6.0.4 on 2026-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_sign',
            field=models.BooleanField(default=False, help_text="Autorise l'employé à signer ses attestations avant envoi."),
        ),
    ]
