# Generated by Django 6.0.4 on 2026-04-15 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('ABSENCE', 'Abnormal Absence'), ('UNDERSTAFFING', 'Understaffing Risk'), ('PERFORMANCE', 'Performance Decline'), ('LEAVE_CONCENTRATION', 'Leave Concentration')], max_length=25)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='employees.department')),
            ],
            options={
                'db_table': 'ai_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction_type', models.CharField(choices=[('LEAVE_FORECAST', 'Leave Forecast'), ('LATE_PATTERN', 'Late Arrival Pattern')], max_length=20)),
                ('data', models.JSONField()),
                ('valid_until', models.DateTimeField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='employees.department')),
            ],
            options={
                'db_table': 'ai_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('STAFFING', 'Staffing'), ('PERFORMANCE', 'Performance'), ('TRAINING', 'Training'), ('WELLBEING', 'Wellbeing')], max_length=15)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=15)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('affected_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='employees.department')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
