# Generated by Django 6.0.4 on 2026-05-14 02:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_numero_somme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePromotionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadre', models.CharField(blank=True, help_text="Ex: Professeur de l'Enseignement Superieur", max_length=100)),
                ('current_grade_code', models.CharField(blank=True, help_text='Code de la classe: A, B, C, D', max_length=10)),
                ('current_grade_label', models.CharField(blank=True, help_text='Ex: Professeur Habilite Classe A', max_length=200)),
                ('current_echelon', models.PositiveSmallIntegerField(default=1, help_text='Rتبة actuelle (1-6)')),
                ('current_indice', models.PositiveIntegerField(default=0, help_text='Indice brut de traitement actuel')),
                ('institution', models.CharField(default='الكلية متعددة التخصصات تارودانت', help_text="Nom de l'institution en arabe", max_length=300)),
                ('last_echelon_promotion_date', models.DateField(blank=True, null=True)),
                ('last_grade_promotion_date', models.DateField(blank=True, null=True)),
                ('titularisation_date', models.DateField(blank=True, null=True)),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('requires_exam', models.BooleanField(default=False)),
                ('exam_passed', models.BooleanField(default=False)),
                ('habilitation_obtained', models.BooleanField(default=False)),
                ('sanctions_count', models.PositiveSmallIntegerField(default=0)),
                ('tableau_count', models.PositiveSmallIntegerField(default=0, help_text='Nb inscriptions tableau sans benefice')),
                ('eligibility_override', models.BooleanField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_profile', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_promotion_profiles',
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_type', models.CharField(choices=[('PROFESSOR', 'Professeur'), ('STAFF', 'Personnel administratif')], max_length=10)),
                ('cadre', models.CharField(help_text='Ex: Professeur Habilite, Technicien', max_length=100)),
                ('current_grade_code', models.CharField(help_text='Ex: A, B, C, D', max_length=10)),
                ('current_echelon', models.PositiveSmallIntegerField()),
                ('promotion_type', models.CharField(choices=[('ECHELON', 'Promotion en Rتبة (Echelon)'), ('GRADE', 'Nomination en Cadre (Grade)')], max_length=10)),
                ('min_years_in_echelon', models.PositiveSmallIntegerField(default=2)),
                ('min_evaluation_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('requires_exam', models.BooleanField(default=False)),
                ('requires_habilitation', models.BooleanField(default=False)),
                ('no_active_sanctions', models.BooleanField(default=True)),
                ('next_echelon', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_grade_code', models.CharField(blank=True, max_length=10)),
                ('next_cadre', models.CharField(blank=True, max_length=100)),
                ('next_indice', models.PositiveIntegerField(blank=True, help_text='Indice brut de traitement apres promotion', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'promotion_rules',
                'ordering': ['employee_type', 'cadre', 'current_echelon'],
                'unique_together': {('employee_type', 'cadre', 'current_grade_code', 'current_echelon', 'promotion_type')},
            },
        ),
        migrations.CreateModel(
            name='PromotionTableInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_type', models.CharField(choices=[('ECHELON', 'جدول اقتراح الترقية في الرتبة'), ('GRADE_TITLE', 'جدول اقتراح التسمية في إطار أستاذ محاضر مؤهل'), ('TITULARISATION', 'جدول اقتراح الترسيم')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('cadre_filter', models.CharField(blank=True, help_text='Cadre filtre pour ce tableau (ex: PESA, MCH)', max_length=200)),
                ('title_ar', models.CharField(blank=True, help_text='Titre arabe du tableau', max_length=300)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Valide'), ('ARCHIVED', 'Archive')], default='DRAFT', max_length=15)),
                ('employees_data', models.JSONField(default=list, help_text='Array of row objects matching official columns')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='promotions/pdf/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotion_tables', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_promotion_tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promotion_table_instances',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion_type', models.CharField(max_length=20)),
                ('old_cadre', models.CharField(blank=True, max_length=100)),
                ('new_cadre', models.CharField(blank=True, max_length=100)),
                ('old_grade_code', models.CharField(blank=True, max_length=10)),
                ('new_grade_code', models.CharField(blank=True, max_length=10)),
                ('old_echelon', models.PositiveSmallIntegerField()),
                ('new_echelon', models.PositiveSmallIntegerField()),
                ('old_indice', models.PositiveIntegerField()),
                ('new_indice', models.PositiveIntegerField()),
                ('seniority_date', models.DateField(blank=True, help_text="Date d'anciennete dans l'ancien echelon", null=True)),
                ('effective_date', models.DateField()),
                ('decision_number', models.CharField(blank=True, max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='promotions/decisions/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='employees.employee')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_promotions', to=settings.AUTH_USER_MODEL)),
                ('table_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='promotions.promotiontableinstance')),
            ],
            options={
                'db_table': 'promotion_history',
                'ordering': ['-effective_date'],
            },
        ),
    ]
