# Generated by Django 6.0.4 on 2026-04-15 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('GENERATE', 'Generation'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Deconnexion')], max_length=15)),
                ('target_type', models.CharField(help_text='Model name, e.g. "DocumentRequest", "Employee"', max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='ID of the affected object.', max_length=100)),
                ('description', models.TextField(help_text='Human-readable description of the action.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context (old values, new values, etc.).')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
