# Generated by Django 6.0.4 on 2026-04-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_HR', 'Admin / HR'), ('DEPARTMENT_HEAD', 'Department Head'), ('PROFESSOR', 'Professor'), ('STAFF', 'Administrative Staff'), ('STUDENT', 'Student')], default='STAFF', max_length=20),
        ),
    ]
