# Generated by Django 6.0.4 on 2026-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN_HR', 'Admin / HR'), ('DEPARTMENT_HEAD', 'Department Head'), ('PROFESSOR', 'Professor'), ('STAFF', 'Administrative Staff'), ('STUDENT', 'Student')], default='STAFF', max_length=20),
        ),
    ]
