# Generated by Django 6.0.4 on 2026-04-15 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_type', models.CharField(choices=[('ATTESTATION_TRAVAIL', 'Attestation de travail'), ('ATTESTATION_SALAIRE', 'Attestation de salaire'), ('ATTESTATION_CONGE', 'Attestation de conge'), ('ATTESTATION_SCOLARITE', 'Attestation de scolarite'), ('ATTESTATION_STAGE', 'Attestation de stage'), ('ATTESTATION_REUSSITE', 'Attestation de reussite')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Rejetee'), ('GENERATED', 'Generee')], default='PENDING', max_length=15)),
                ('message', models.TextField(blank=True, help_text='Optional message or note from the requester.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
