# Generated by Django 6.0.4 on 2026-04-15 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nom du modele, ex: "Attestation de travail"', max_length=200)),
                ('category', models.CharField(choices=[('ATTESTATION', 'Attestation'), ('ORDRE_MISSION', 'Ordre de mission'), ('AUTORISATION', 'Autorisation'), ('AUTRE', 'Autre')], default='ATTESTATION', max_length=20)),
                ('language', models.CharField(choices=[('FR', 'Francais'), ('AR', 'Arabe')], default='FR', max_length=2)),
                ('description', models.TextField(blank=True, help_text='Description interne visible uniquement par les admins.')),
                ('is_active', models.BooleanField(default=True, help_text='Les modeles inactifs ne sont plus proposés aux utilisateurs.')),
                ('content', models.TextField(help_text='Contenu HTML du document avec des variables {{nom_variable}}.')),
                ('variables', models.JSONField(default=list, help_text='Liste JSON des variables disponibles dans ce modele.')),
                ('header_html', models.TextField(blank=True, help_text='En-tete HTML (logo universite, nom faculte, etc.).')),
                ('footer_html', models.TextField(blank=True, help_text='Pied de page HTML (adresse, telephone, etc.).')),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'institution pour l'en-tete.", null=True, upload_to='templates/logos/')),
                ('custom_css', models.TextField(blank=True, help_text='CSS personnalise pour ce modele (marges, polices, etc.).')),
            ],
            options={
                'db_table': 'document_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Rejetee'), ('GENERATED', 'Generee')], default='PENDING', max_length=15)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Données manuelles saisies par le demandeur.')),
                ('message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Le modele de document choisi.', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='certificates.documenttemplate')),
            ],
            options={
                'db_table': 'document_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(upload_to='generated_docs/%Y/%m/')),
                ('rendered_html', models.TextField(help_text='Snapshot of the rendered HTML used to generate this PDF.')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_docs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='certificates.documentrequest')),
            ],
            options={
                'db_table': 'generated_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiee'), ('APPROVED', 'Approuvee'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminee'), ('CANCELLED', 'Annulee')], default='PLANNED', max_length=15)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_missions', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='missions', to='certificates.generateddocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='employees.employee')),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='CertificateRequest',
        ),
    ]
