# Generated by Django 6.0.4 on 2026-04-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_documenttemplate_documentrequest_generateddocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Tous'), ('EMPLOYEE', 'Personnel (enseignants et administratifs)'), ('STUDENT', 'Etudiants')], default='ALL', help_text='Qui peut demander ce document: tous, personnel, ou etudiants.', max_length=10),
        ),
    ]
