# Generated by Django 6.0.4 on 2026-05-04 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_documenttemplate_target_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureStamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SIGNATURE', 'Signature'), ('STAMP', 'Cachet')], max_length=10)),
                ('label', models.CharField(help_text='Ex: Signature du Doyen', max_length=100)),
                ('image', models.ImageField(upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'signature_stamps',
                'ordering': ['kind', '-created_at'],
            },
        ),
    ]
