# Generated by Django 6.0.4 on 2026-05-05 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_signature_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Le modele de document choisi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='certificates.documenttemplate'),
        ),
    ]
