# Generated by Django 6.0.4 on 2026-05-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_template_set_null_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Tous'), ('EMPLOYEE', 'Tout le personnel (enseignants + administratifs)'), ('PROFESSOR', 'Professeurs uniquement'), ('DEPARTMENT_HEAD', 'Chefs de departement uniquement'), ('STAFF', 'Personnel administratif uniquement'), ('STUDENT', 'Etudiants uniquement')], default='ALL', help_text='Qui peut demander ce document. Controlable par le super admin.', max_length=20),
        ),
    ]
