# Generated by Django 6.0.4 on 2026-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_add_role_specific_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='request_attachments/%Y/%m/'),
        ),
    ]
