# Generated by Django 6.0.4 on 2026-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_documentrequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PENDING_SIGNATURE', 'En attente de signature'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Rejetee'), ('GENERATED', 'Generee')], default='PENDING', max_length=20),
        ),
    ]
