# Generated by Django 6.0.4 on 2026-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_documentrequest_signed_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='requires_signature',
            field=models.BooleanField(default=False, help_text='Si activé, le professeur doit signer le document avant validation finale.'),
        ),
    ]
