from django.db import models
from apps.core.models import TimeStampedModel


class Alert(TimeStampedModel):
    """Department-level alerts generated by the AI engine."""
    class Severity(models.TextChoices):
        INFO = 'INFO', 'Info'
        WARNING = 'WARNING', 'Warning'
        CRITICAL = 'CRITICAL', 'Critical'

    class Category(models.TextChoices):
        ABSENCE = 'ABSENCE', 'Abnormal Absence'
        UNDERSTAFFING = 'UNDERSTAFFING', 'Understaffing Risk'
        PERFORMANCE = 'PERFORMANCE', 'Performance Decline'
        LEAVE_CONCENTRATION = 'LEAVE_CONCENTRATION', 'Leave Concentration'

    department = models.ForeignKey(
        'employees.Department', on_delete=models.CASCADE, related_name='alerts',
    )
    category = models.CharField(max_length=25, choices=Category.choices)
    severity = models.CharField(max_length=10, choices=Severity.choices)
    title = models.CharField(max_length=200)
    description = models.TextField()
    metric_value = models.FloatField()
    threshold_value = models.FloatField()
    is_active = models.BooleanField(default=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    acknowledged_by = models.ForeignKey(
        'accounts.User', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='acknowledged_alerts',
    )

    class Meta:
        db_table = 'ai_alerts'
        ordering = ['-created_at']


class Recommendation(TimeStampedModel):
    """AI-generated recommendations for HR management."""
    class Category(models.TextChoices):
        STAFFING = 'STAFFING', 'Staffing'
        PERFORMANCE = 'PERFORMANCE', 'Performance'
        TRAINING = 'TRAINING', 'Training'
        WELLBEING = 'WELLBEING', 'Wellbeing'

    class Status(models.TextChoices):
        NEW = 'NEW', 'New'
        ACKNOWLEDGED = 'ACKNOWLEDGED', 'Acknowledged'
        DISMISSED = 'DISMISSED', 'Dismissed'

    category = models.CharField(max_length=15, choices=Category.choices)
    priority = models.PositiveSmallIntegerField(default=50)
    title = models.CharField(max_length=200)
    description = models.TextField()
    affected_department = models.ForeignKey(
        'employees.Department', on_delete=models.CASCADE,
        null=True, blank=True, related_name='recommendations',
    )
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.NEW)
    expires_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'ai_recommendations'
        ordering = ['-priority', '-created_at']
