# Generated by Django 6.0.4 on 2026-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notification_attachments/%Y/%m/'),
        ),
    ]
