# Generated by Django 6.0.5 on 2026-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('ATTENDANCE_ALERT', 'Attendance Alert'), ('PAYSLIP_READY', 'Payslip Ready'), ('EVALUATION_DUE', 'Evaluation Due'), ('EVALUATION_COMPLETE', 'Evaluation Completed'), ('DOCUMENT_REQUEST', 'Document Request'), ('DOCUMENT_APPROVED', 'Document Approved'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_SIGNED', 'Document Signed'), ('REQUEST_SUBMITTED', 'Request Submitted'), ('SYSTEM', 'System Notification')], max_length=25),
        ),
    ]
